# Generated by Django 5.2.17 on 2026-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=2),
        ),
    ]
