# Generated by Django 5.2.17 on 2026-10-09 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True, db_default='', default='', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
