# Generated by Django 5.2.17 on 2026-10-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='edited',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='next_todo',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='todos.todo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Every day'), ('weekly', 'Every week'), ('monthly', 'Every month')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat_day',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
