# Generated by Django 5.2.17 on 2026-10-09 13:00

from django.db import migrations

from todos.data_migrations import delete_todos_without_owner


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todo_owner'),
    ]

    operations = [
        migrations.RunPython(delete_todos_without_owner, migrations.RunPython.noop),
    ]
