# Generated by Django 5.2.17 on 2026-10-09 14:14

from django.db import migrations

from todos.data_migrations import delete_todos_without_a_list


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_todolist'),
    ]

    operations = [
        migrations.RunPython(delete_todos_without_a_list, migrations.RunPython.noop),
    ]
