# Generated by Django 5.2.17 on 2026-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
