# Generated by Django 5.2.17 on 2026-10-09 14:45

from django.db import migrations

from todos.data_migrations import number_existing_todos


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_todo_position'),
    ]

    operations = [
        migrations.RunPython(number_existing_todos, migrations.RunPython.noop),
    ]
